# This file was generated by GoReleaser. DO NOT EDIT.
cask "httc" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "42494ec42c599b8a7a5ae56c3797ac83bbbdf20e9f15f3608a42b5c8b1713de4"
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b24ab1a3a0142c5265280ac8a1455a16b15fae3dc16c0bbe2672e1bd2f0cfbc"
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3c53b8178c9d58e680b57d5f6651542b5289cfb31e630e28a1869380df965b5"
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74170994048cac0ecaa9d8553b6f250839b447cbc4d3d0d03ee1aa6f1bd84786"
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "httc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httc"]
    end
  end

  # No zap stanza required

end
