# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbot" do
  name "sbot"
  desc ""
  homepage ""
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbot"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_amd64.tar.gz"
      sha256 "bec67b8f6420669d6a1f77e441f5d8809a0cd90a9c6e28bb0ad1b69e074d14bc"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_arm64.tar.gz"
      sha256 "b89a12b4210f40b9766b495809b3115307a9aee61ebac7f3fc45e44dd66e42c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_amd64.tar.gz"
      sha256 "1bf0e5ab75e64d154c04a40f4821470fd690f2813276ce01424ea2fa1a02ee5e"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_arm64.tar.gz"
      sha256 "6aa113344ee910a4a350f37d021428910830ec5590b013d5cfb185050c7e4fae"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbot"]
    end
  end

  # No zap stanza required
end
