# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbottui" do
  name "sbottui"
  desc ""
  homepage ""
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbottui"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_amd64.tar.gz"
      sha256 "6884436811f5e472299bf3e039f1ec7de24531dffd0c1b6cc1f21a9d2429f41e"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_arm64.tar.gz"
      sha256 "ca0cb5f162e9fa212ed42be3ec0b3356cbdc15dc95e717bdf6db8e4bab7fb697"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_amd64.tar.gz"
      sha256 "39705fae5ccf3d4bdeff317f4076ff4472194cebe5649628bb40255597ef4605"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_arm64.tar.gz"
      sha256 "6f2b255cad222d01dc91fbcbe8b9fbf376f7a2bc244965ee08f2ab9119e46080"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbottui"]
    end
  end

  # No zap stanza required
end
