# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbot" do
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_amd64.tar.gz"
      sha256 "e1fab7f830737efc34cf715ded803bf4aab514d04d38f7bb2f6de3d205cd554d"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_arm64.tar.gz"
      sha256 "4f1dfe6d25c0b81263e595bdacb3752bf930809337c6bccc9dbafbb776a9ec5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_amd64.tar.gz"
      sha256 "92bc5f8002b639d2b52362e5ed391493c03b455e7c20a71d3c3b97456ad6fb7f"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_arm64.tar.gz"
      sha256 "72e34b9df7976c468696e3773f674966b35e1c80bbb7edb9885db81d82844e52"
    end
  end

  name "sbot"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbot"]
    end
  end

  # No zap stanza required

end
