# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbottui" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_amd64.tar.gz"
      sha256 "22ed5f51c900cfd4138fc73fae45a6e73e1779c8272690a6b740cfb4ff071c47"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_arm64.tar.gz"
      sha256 "dcbf3e90a84e42d42573eec4824c42b6f162f6bfdbfbd355605b1d40af9e7e4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_amd64.tar.gz"
      sha256 "86ae46b89d992ae4469e6292c678273ebeae0cf3501b870dcb0672261fef3799"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_arm64.tar.gz"
      sha256 "7b033212faeddac030f0bcdaf7b1642e685ba33094aa0da5a732e7a21257881f"
    end
  end

  name "sbottui"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbottui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbottui"]
    end
  end

  # No zap stanza required

end
