# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbottui" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "bbde439bd680c60cf35eaeab937d1d9742b74a0e7c88aab1bca62356257624b2"
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aa6f8f0abb44331b5ae96f7163ed504a753d753c4d0c2210dc07daccde0c39e"
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ee262166f3439eb30128231c33acf0211d8a64ec3b51371a2b076588708d8ce"
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c0ea7fb3ddf15f2e811d97464f787826a0cae844d674b15bb227bdc790ac86d"
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sbottui"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbottui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbottui"]
    end
  end

  # No zap stanza required

end
