# This file was generated by GoReleaser. DO NOT EDIT.
cask "yabumi" do
  name "yabumi"
  desc ""
  homepage ""
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yabumi"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_amd64.tar.gz"
      sha256 "d1fad09aac73737c809c8e25070bd64015751167ed71c832198772c92126faac"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_arm64.tar.gz"
      sha256 "b64e5062297a0ded7a47533d8ad6165110afbf1b3039470bb31296372d4ae2de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_amd64.tar.gz"
      sha256 "cc7699aa2c7a3506b79b01b74b32def83a37280adcc915c05bf6276f9d1af2a2"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_arm64.tar.gz"
      sha256 "7258800ec2937827b3c860f8689e2c925887165e81d05096f0df060f974594d6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yabumi"]
    end
  end

  # No zap stanza required
end
