# This file was generated by GoReleaser. DO NOT EDIT.
cask "yabumi" do
  name "yabumi"
  desc ""
  homepage ""
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yabumi"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_amd64.tar.gz"
      sha256 "c1d3c70cbb52d241623ec4d0a809c83d8bcf5181f9e1a695a48bf3cd7799e722"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_arm64.tar.gz"
      sha256 "b1c9e150127cdf8d8dc205fa9fa0b6984b137611afa7fccaad1410a0202393f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_amd64.tar.gz"
      sha256 "6a203dd76db673d737bf7604f03004aca0eea0ae234ce42d10b33bc618839479"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_arm64.tar.gz"
      sha256 "ca1b8c61c82bd0007dc813b9dcfa685e51fb282a97b9b2b40bd165935777f76e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yabumi"]
    end
  end

  # No zap stanza required
end
