# This file was generated by GoReleaser. DO NOT EDIT.
cask "yabumi" do
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_amd64.tar.gz"
      sha256 "655f8d9231a5896889bcce37e19cc4ea0be4600b9e4e85a2864828b52e59e912"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_darwin_arm64.tar.gz"
      sha256 "83ecdf8bc94d3f0ae1d758da908371de7555f6f043aa83860e713e69e30caf6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_amd64.tar.gz"
      sha256 "7fc038e30b89f7a41fa642ede5e25e1f3edd5c05f18d63727a33675e2b20bd8d"
    end
    on_arm do
      url "https://github.com/yteraoka/yabumi/releases/download/v#{version}/yabumi_#{version}_linux_arm64.tar.gz"
      sha256 "e4d30e474361ec25d0e0290b123f7ed5c893e901f68d62cf8c3c70232e0db9e1"
    end
  end

  name "yabumi"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yabumi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yabumi"]
    end
  end

  # No zap stanza required

end
